server:
  port: ${PORT:8081}

spring:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://postgres:5432/sgaf_main}
    username: ${POSTGRES_USER:sgaf}
    password: ${POSTGRES_PASSWORD:changeme}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true

springdoc:
  api-docs:
    path: /api/usuarios/v3/api-docs
  swagger-ui:
    path: /api/usuarios/swagger-ui.html
    use-root-path: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
